window.esdocSearchIndex = [
  [
    "./packages/oo7-substrate/src/addressbook.js~addressbook",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html",
    "<span>AddressBook</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/addressBook.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~badgeabi",
    "variable/index.html#static-variable-BadgeABI",
    "<span>BadgeABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~badgeregabi",
    "variable/index.html#static-variable-BadgeRegABI",
    "<span>BadgeRegABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7/src/bond.js~bond",
    "class/packages/oo7/src/bond.js~Bond.html",
    "<span>Bond</span> <span class=\"search-result-import-path\">./packages/oo7/src/bond.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/bondcache.js~bondcache",
    "class/packages/oo7/src/bondCache.js~BondCache.html",
    "<span>BondCache</span> <span class=\"search-result-import-path\">./packages/oo7/src/bondCache.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/bondproxy.js~bondproxy",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html",
    "<span>BondProxy</span> <span class=\"search-result-import-path\">./packages/oo7/src/bondProxy.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/index.js~bonds",
    "class/packages/oo7-parity/src/index.js~Bonds.html",
    "<span>Bonds</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/defaultbond.js~defaultbond",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html",
    "<span>DefaultBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/defaultBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~githubhintabi",
    "variable/index.html#static-variable-GitHubHintABI",
    "<span>GitHubHintABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/polkadot-identicon/lib/index.js~identicon",
    "class/packages/polkadot-identicon/lib/index.js~Identicon.html",
    "<span>Identicon</span> <span class=\"search-result-import-path\">./packages/polkadot-identicon/lib/index.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/latchbond.js~latchbond",
    "class/packages/oo7/src/latchBond.js~LatchBond.html",
    "<span>LatchBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/latchBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-substrate/src/nodeservice.js~nodeservice",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html",
    "<span>NodeService</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/nodeService.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/notreadybond.js~notreadybond",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html",
    "<span>NotReadyBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/notReadyBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~operationsabi",
    "variable/index.html#static-variable-OperationsABI",
    "<span>OperationsABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7/src/reactivebond.js~reactivebond",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html",
    "<span>ReactiveBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/reactiveBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/reactivepromise.js~reactivepromise",
    "class/packages/oo7/src/reactivePromise.js~ReactivePromise.html",
    "<span>ReactivePromise</span> <span class=\"search-result-import-path\">./packages/oo7/src/reactivePromise.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/readybond.js~readybond",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html",
    "<span>ReadyBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/readyBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~registryextras",
    "variable/index.html#static-variable-RegistryExtras",
    "<span>RegistryExtras</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-substrate/src/secretstore.js~secretstore",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html",
    "<span>SecretStore</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/secretStore.js</span>",
    "class"
  ],
  [
    "./packages/oo7/src/timebond.js~timebond",
    "class/packages/oo7/src/timeBond.js~TimeBond.html",
    "<span>TimeBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/timeBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~tokenabi",
    "variable/index.html#static-variable-TokenABI",
    "<span>TokenABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~tokenregabi",
    "variable/index.html#static-variable-TokenRegABI",
    "<span>TokenRegABI</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7/src/transformbond.js~transformbond",
    "class/packages/oo7/src/transformBond.js~TransformBond.html",
    "<span>TransformBond</span> <span class=\"search-result-import-path\">./packages/oo7/src/transformBond.js</span>",
    "class"
  ],
  [
    "./packages/oo7-parity/src/abis/index.js~abipolyfill",
    "function/index.html#static-function-abiPolyfill",
    "<span>abiPolyfill</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/abis/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/addressbook.js~addressbook",
    "function/index.html#static-function-addressBook",
    "<span>addressBook</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/addressBook.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~asciitohex",
    "variable/index.html#static-variable-asciiToHex",
    "<span>asciiToHex</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/index.js~bonds",
    "variable/index.html#static-variable-bonds",
    "<span>bonds</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~bytestohex",
    "variable/index.html#static-variable-bytesToHex",
    "<span>bytesToHex</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~capitalizefirstletter",
    "function/index.html#static-function-capitalizeFirstLetter",
    "<span>capitalizeFirstLetter</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~cleanup",
    "function/index.html#static-function-cleanup",
    "<span>cleanup</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~combinevalue",
    "function/index.html#static-function-combineValue",
    "<span>combineValue</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/transact.js~composetransaction",
    "function/index.html#static-function-composeTransaction",
    "<span>composeTransaction</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/transact.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/index.js~createbonds",
    "function/index.html#static-function-createBonds",
    "<span>createBonds</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~defdenom",
    "function/index.html#static-function-defDenom",
    "<span>defDenom</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~denominationmultiplier",
    "function/index.html#static-function-denominationMultiplier",
    "<span>denominationMultiplier</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~denominations",
    "variable/index.html#static-variable-denominations",
    "<span>denominations</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~formatbalance",
    "function/index.html#static-function-formatBalance",
    "<span>formatBalance</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~formatblocknumber",
    "function/index.html#static-function-formatBlockNumber",
    "<span>formatBlockNumber</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~formattoexponential",
    "function/index.html#static-function-formatToExponential",
    "<span>formatToExponential</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~formatvalue",
    "function/index.html#static-function-formatValue",
    "<span>formatValue</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~formatvaluenodenom",
    "function/index.html#static-function-formatValueNoDenom",
    "<span>formatValueNoDenom</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~hextoascii",
    "variable/index.html#static-variable-hexToAscii",
    "<span>hexToAscii</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~interpretquantity",
    "function/index.html#static-function-interpretQuantity",
    "<span>interpretQuantity</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~interpretrender",
    "function/index.html#static-function-interpretRender",
    "<span>interpretRender</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~isaddressvalid",
    "function/index.html#static-function-isAddressValid",
    "<span>isAddressValid</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/index.js~isnotowned",
    "function/index.html#static-function-isNotOwned",
    "<span>isNotOwned</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~isnulldata",
    "function/index.html#static-function-isNullData",
    "<span>isNullData</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/index.js~isowned",
    "function/index.html#static-function-isOwned",
    "<span>isOwned</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/metadata.js~metadata",
    "variable/index.html#static-variable-metadata",
    "<span>metadata</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/metadata.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-substrate/src/nodeservice.js~nodeservice",
    "function/index.html#static-function-nodeService",
    "<span>nodeService</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/nodeService.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/index.js~options",
    "variable/index.html#static-variable-options",
    "<span>options</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/index.js</span>",
    "variable"
  ],
  [
    "./packages/oo7-substrate/src/transact.js~post",
    "function/index.html#static-function-post",
    "<span>post</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/transact.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/pretty.js~pretty",
    "function/index.html#static-function-pretty",
    "<span>pretty</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/pretty.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~removesigningprefix",
    "function/index.html#static-function-removeSigningPrefix",
    "<span>removeSigningPrefix</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/secretstore.js~secretstore",
    "function/index.html#static-function-secretStore",
    "<span>secretStore</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/secretStore.js</span>",
    "function"
  ],
  [
    "./packages/oo7-substrate/src/nodeservice.js~setnodeuri",
    "function/index.html#static-function-setNodeUri",
    "<span>setNodeUri</span> <span class=\"search-result-import-path\">./packages/oo7-substrate/src/nodeService.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~sha3",
    "function/index.html#static-function-sha3",
    "<span>sha3</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~singleton",
    "function/index.html#static-function-singleton",
    "<span>singleton</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~splitsignature",
    "function/index.html#static-function-splitSignature",
    "<span>splitSignature</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~splitvalue",
    "function/index.html#static-function-splitValue",
    "<span>splitValue</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "./packages/oo7-parity/src/utils/index.js~tochecksumaddress",
    "function/index.html#static-function-toChecksumAddress",
    "<span>toChecksumAddress</span> <span class=\"search-result-import-path\">./packages/oo7-parity/src/utils/index.js</span>",
    "function"
  ],
  [
    "packages/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "packages/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "packages/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "packages/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "packages/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "packages/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "packages/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "packages/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "packages/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "packages/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "packages/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "packages/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "packages/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "packages/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "packages/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "packages/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "packages/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "packages/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "packages/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "packages/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "packages/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "packages/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "packages/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "packages/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "packages/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "packages/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "packages/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "packages/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "packages/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "packages/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "packages/.external-ecmascript.js~String",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "packages/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "packages/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "packages/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "packages/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "packages/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "packages/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "packages/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "packages/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "packages/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "packages/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "packages/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "packages/.external-ecmascript.js~function",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "packages/.external-ecmascript.js~null",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "packages/.external-ecmascript.js~number",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "packages/.external-ecmascript.js~object",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "packages/.external-ecmascript.js~string",
    "external"
  ],
  [
    "packages/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "packages/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "packages/oo7-parity/src/abis/index.js",
    "file/packages/oo7-parity/src/abis/index.js.html",
    "packages/oo7-parity/src/abis/index.js",
    "file"
  ],
  [
    "packages/oo7-parity/src/index.js",
    "file/packages/oo7-parity/src/index.js.html",
    "packages/oo7-parity/src/index.js",
    "file"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#accounts",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-accounts",
    "packages/oo7-parity/src/index.js~Bonds#accounts",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#accountsinfo",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-accountsInfo",
    "packages/oo7-parity/src/index.js~Bonds#accountsInfo",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#allaccontsinfo",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-allAccontsInfo",
    "packages/oo7-parity/src/index.js~Bonds#allAccontsInfo",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#author",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-author",
    "packages/oo7-parity/src/index.js~Bonds#author",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#authoring",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-authoring",
    "packages/oo7-parity/src/index.js~Bonds#authoring",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#badgereg",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-badgereg",
    "packages/oo7-parity/src/index.js~Bonds#badgereg",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#badges",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-badges",
    "packages/oo7-parity/src/index.js~Bonds#badges",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#badgesof",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-badgesOf",
    "packages/oo7-parity/src/index.js~Bonds#badgesOf",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#balance",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-balance",
    "packages/oo7-parity/src/index.js~Bonds#balance",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#blockbyhash",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-blockByHash",
    "packages/oo7-parity/src/index.js~Bonds#blockByHash",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#blockbynumber",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-blockByNumber",
    "packages/oo7-parity/src/index.js~Bonds#blockByNumber",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#blocknumber",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-blockNumber",
    "packages/oo7-parity/src/index.js~Bonds#blockNumber",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#blocktransactioncount",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-blockTransactionCount",
    "packages/oo7-parity/src/index.js~Bonds#blockTransactionCount",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#blocks",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-blocks",
    "packages/oo7-parity/src/index.js~Bonds#blocks",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#calltx",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-callTx",
    "packages/oo7-parity/src/index.js~Bonds#callTx",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#chainid",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-chainId",
    "packages/oo7-parity/src/index.js~Bonds#chainId",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#chainname",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-chainName",
    "packages/oo7-parity/src/index.js~Bonds#chainName",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#chainstatus",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-chainStatus",
    "packages/oo7-parity/src/index.js~Bonds#chainStatus",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#clientversion",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-clientVersion",
    "packages/oo7-parity/src/index.js~Bonds#clientVersion",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#code",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-code",
    "packages/oo7-parity/src/index.js~Bonds#code",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#consensuscapability",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-consensusCapability",
    "packages/oo7-parity/src/index.js~Bonds#consensusCapability",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#constructor",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-constructor-constructor",
    "packages/oo7-parity/src/index.js~Bonds#constructor",
    "method"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#dappsinterface",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-dappsInterface",
    "packages/oo7-parity/src/index.js~Bonds#dappsInterface",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#dappsport",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-dappsPort",
    "packages/oo7-parity/src/index.js~Bonds#dappsPort",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#defaultaccount",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-defaultAccount",
    "packages/oo7-parity/src/index.js~Bonds#defaultAccount",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#defaultextradata",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-defaultExtraData",
    "packages/oo7-parity/src/index.js~Bonds#defaultExtraData",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#deploycontract",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-deployContract",
    "packages/oo7-parity/src/index.js~Bonds#deployContract",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#enode",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-enode",
    "packages/oo7-parity/src/index.js~Bonds#enode",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#estimategas",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-estimateGas",
    "packages/oo7-parity/src/index.js~Bonds#estimateGas",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#ethprotocolversion",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-ethProtocolVersion",
    "packages/oo7-parity/src/index.js~Bonds#ethProtocolVersion",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#extradata",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-extraData",
    "packages/oo7-parity/src/index.js~Bonds#extraData",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#findblock",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-findBlock",
    "packages/oo7-parity/src/index.js~Bonds#findBlock",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#future",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-future",
    "packages/oo7-parity/src/index.js~Bonds#future",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#gasceiltarget",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-gasCeilTarget",
    "packages/oo7-parity/src/index.js~Bonds#gasCeilTarget",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#gasfloortarget",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-gasFloorTarget",
    "packages/oo7-parity/src/index.js~Bonds#gasFloorTarget",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#gasprice",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-gasPrice",
    "packages/oo7-parity/src/index.js~Bonds#gasPrice",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#gaspricehistogram",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-gasPriceHistogram",
    "packages/oo7-parity/src/index.js~Bonds#gasPriceHistogram",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#githubhint",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-githubhint",
    "packages/oo7-parity/src/index.js~Bonds#githubhint",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#hardwareaccountsinfo",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-hardwareAccountsInfo",
    "packages/oo7-parity/src/index.js~Bonds#hardwareAccountsInfo",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#hashcontent",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-hashContent",
    "packages/oo7-parity/src/index.js~Bonds#hashContent",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#hashrate",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-hashrate",
    "packages/oo7-parity/src/index.js~Bonds#hashrate",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#head",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-head",
    "packages/oo7-parity/src/index.js~Bonds#head",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#height",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-height",
    "packages/oo7-parity/src/index.js~Bonds#height",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#listening",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-listening",
    "packages/oo7-parity/src/index.js~Bonds#listening",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#local",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-local",
    "packages/oo7-parity/src/index.js~Bonds#local",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#makecontract",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-makeContract",
    "packages/oo7-parity/src/index.js~Bonds#makeContract",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#me",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-me",
    "packages/oo7-parity/src/index.js~Bonds#me",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#mingasprice",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-minGasPrice",
    "packages/oo7-parity/src/index.js~Bonds#minGasPrice",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#mode",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-mode",
    "packages/oo7-parity/src/index.js~Bonds#mode",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#nextnonce",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-nextNonce",
    "packages/oo7-parity/src/index.js~Bonds#nextNonce",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#nodename",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-nodeName",
    "packages/oo7-parity/src/index.js~Bonds#nodeName",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#nodeport",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-nodePort",
    "packages/oo7-parity/src/index.js~Bonds#nodePort",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#nonce",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-nonce",
    "packages/oo7-parity/src/index.js~Bonds#nonce",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#operations",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-operations",
    "packages/oo7-parity/src/index.js~Bonds#operations",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#peercount",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-peerCount",
    "packages/oo7-parity/src/index.js~Bonds#peerCount",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#peers",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-peers",
    "packages/oo7-parity/src/index.js~Bonds#peers",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#pending",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-pending",
    "packages/oo7-parity/src/index.js~Bonds#pending",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#pendingstats",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-pendingStats",
    "packages/oo7-parity/src/index.js~Bonds#pendingStats",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#post",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-post",
    "packages/oo7-parity/src/index.js~Bonds#post",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#receipt",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-receipt",
    "packages/oo7-parity/src/index.js~Bonds#receipt",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#registry",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-registry",
    "packages/oo7-parity/src/index.js~Bonds#registry",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#releaseinfo",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-releaseInfo",
    "packages/oo7-parity/src/index.js~Bonds#releaseInfo",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#replaytx",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-replayTx",
    "packages/oo7-parity/src/index.js~Bonds#replayTx",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#sign",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-sign",
    "packages/oo7-parity/src/index.js~Bonds#sign",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#signerport",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-signerPort",
    "packages/oo7-parity/src/index.js~Bonds#signerPort",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#storageat",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-storageAt",
    "packages/oo7-parity/src/index.js~Bonds#storageAt",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#syncing",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-syncing",
    "packages/oo7-parity/src/index.js~Bonds#syncing",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#time",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-time",
    "packages/oo7-parity/src/index.js~Bonds#time",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#tokenreg",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-tokenreg",
    "packages/oo7-parity/src/index.js~Bonds#tokenreg",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#tokens",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-tokens",
    "packages/oo7-parity/src/index.js~Bonds#tokens",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#tokensof",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-tokensOf",
    "packages/oo7-parity/src/index.js~Bonds#tokensOf",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#transaction",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-transaction",
    "packages/oo7-parity/src/index.js~Bonds#transaction",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#transactionslimit",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-transactionsLimit",
    "packages/oo7-parity/src/index.js~Bonds#transactionsLimit",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#uncle",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-uncle",
    "packages/oo7-parity/src/index.js~Bonds#uncle",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#unclecount",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-uncleCount",
    "packages/oo7-parity/src/index.js~Bonds#uncleCount",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#unsignedcount",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-unsignedCount",
    "packages/oo7-parity/src/index.js~Bonds#unsignedCount",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#upgradeready",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-upgradeReady",
    "packages/oo7-parity/src/index.js~Bonds#upgradeReady",
    "member"
  ],
  [
    "packages/oo7-parity/src/index.js~bonds#versioninfo",
    "class/packages/oo7-parity/src/index.js~Bonds.html#instance-member-versionInfo",
    "packages/oo7-parity/src/index.js~Bonds#versionInfo",
    "member"
  ],
  [
    "packages/oo7-parity/src/utils/index.js",
    "file/packages/oo7-parity/src/utils/index.js.html",
    "packages/oo7-parity/src/utils/index.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js",
    "file/packages/oo7-substrate/src/addressBook.js.html",
    "packages/oo7-substrate/src/addressBook.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#_accounts",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-member-_accounts",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#_accounts",
    "member"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#_byaddress",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-member-_byAddress",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#_byAddress",
    "member"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#_byname",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-member-_byName",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#_byName",
    "member"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#_load",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-_load",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#_load",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#_sync",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-_sync",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#_sync",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#accounts",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-accounts",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#accounts",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#constructor",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-constructor-constructor",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#constructor",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#find",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-find",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#find",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#forget",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-forget",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#forget",
    "method"
  ],
  [
    "packages/oo7-substrate/src/addressbook.js~addressbook#submit",
    "class/packages/oo7-substrate/src/addressBook.js~AddressBook.html#instance-method-submit",
    "packages/oo7-substrate/src/addressBook.js~AddressBook#submit",
    "method"
  ],
  [
    "packages/oo7-substrate/src/bonds.js",
    "file/packages/oo7-substrate/src/bonds.js.html",
    "packages/oo7-substrate/src/bonds.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/codec.js",
    "file/packages/oo7-substrate/src/codec.js.html",
    "packages/oo7-substrate/src/codec.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/denominationinfo.js",
    "file/packages/oo7-substrate/src/denominationInfo.js.html",
    "packages/oo7-substrate/src/denominationInfo.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/index.js",
    "file/packages/oo7-substrate/src/index.js.html",
    "packages/oo7-substrate/src/index.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/metadata.js",
    "file/packages/oo7-substrate/src/metadata.js.html",
    "packages/oo7-substrate/src/metadata.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js",
    "file/packages/oo7-substrate/src/nodeService.js.html",
    "packages/oo7-substrate/src/nodeService.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#backoff",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-backoff",
    "packages/oo7-substrate/src/nodeService.js~NodeService#backoff",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#constructor",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-constructor-constructor",
    "packages/oo7-substrate/src/nodeService.js~NodeService#constructor",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#finalise",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-method-finalise",
    "packages/oo7-substrate/src/nodeService.js~NodeService#finalise",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#index",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-index",
    "packages/oo7-substrate/src/nodeService.js~NodeService#index",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#onreply",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-onReply",
    "packages/oo7-substrate/src/nodeService.js~NodeService#onReply",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#onceopen",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-onceOpen",
    "packages/oo7-substrate/src/nodeService.js~NodeService#onceOpen",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#request",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-method-request",
    "packages/oo7-substrate/src/nodeService.js~NodeService#request",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#start",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-method-start",
    "packages/oo7-substrate/src/nodeService.js~NodeService#start",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#subscribe",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-method-subscribe",
    "packages/oo7-substrate/src/nodeService.js~NodeService#subscribe",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#subscriptions",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-subscriptions",
    "packages/oo7-substrate/src/nodeService.js~NodeService#subscriptions",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#unsubscribe",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-method-unsubscribe",
    "packages/oo7-substrate/src/nodeService.js~NodeService#unsubscribe",
    "method"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#uri",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-uri",
    "packages/oo7-substrate/src/nodeService.js~NodeService#uri",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#uriindex",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-uriIndex",
    "packages/oo7-substrate/src/nodeService.js~NodeService#uriIndex",
    "member"
  ],
  [
    "packages/oo7-substrate/src/nodeservice.js~nodeservice#ws",
    "class/packages/oo7-substrate/src/nodeService.js~NodeService.html#instance-member-ws",
    "packages/oo7-substrate/src/nodeService.js~NodeService#ws",
    "member"
  ],
  [
    "packages/oo7-substrate/src/pretty.js",
    "file/packages/oo7-substrate/src/pretty.js.html",
    "packages/oo7-substrate/src/pretty.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js",
    "file/packages/oo7-substrate/src/secretStore.js.html",
    "packages/oo7-substrate/src/secretStore.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#_byaddress",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-member-_byAddress",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#_byAddress",
    "member"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#_byname",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-member-_byName",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#_byName",
    "member"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#_keys",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-member-_keys",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#_keys",
    "member"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#_load",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-_load",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#_load",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#_sync",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-_sync",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#_sync",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#accountfromphrase",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-accountFromPhrase",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#accountFromPhrase",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#accounts",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-accounts",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#accounts",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#constructor",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-constructor-constructor",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#constructor",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#find",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-find",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#find",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#forget",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-forget",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#forget",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#sign",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-sign",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#sign",
    "method"
  ],
  [
    "packages/oo7-substrate/src/secretstore.js~secretstore#submit",
    "class/packages/oo7-substrate/src/secretStore.js~SecretStore.html#instance-method-submit",
    "packages/oo7-substrate/src/secretStore.js~SecretStore#submit",
    "method"
  ],
  [
    "packages/oo7-substrate/src/srml/balances.js",
    "file/packages/oo7-substrate/src/srml/balances.js.html",
    "packages/oo7-substrate/src/srml/balances.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/srml/democracy.js",
    "file/packages/oo7-substrate/src/srml/democracy.js.html",
    "packages/oo7-substrate/src/srml/democracy.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/srml/session.js",
    "file/packages/oo7-substrate/src/srml/session.js.html",
    "packages/oo7-substrate/src/srml/session.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/srml/staking.js",
    "file/packages/oo7-substrate/src/srml/staking.js.html",
    "packages/oo7-substrate/src/srml/staking.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/ss58.js",
    "file/packages/oo7-substrate/src/ss58.js.html",
    "packages/oo7-substrate/src/ss58.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/storagebond.js",
    "file/packages/oo7-substrate/src/storageBond.js.html",
    "packages/oo7-substrate/src/storageBond.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/subscriptionbond.js",
    "file/packages/oo7-substrate/src/subscriptionBond.js.html",
    "packages/oo7-substrate/src/subscriptionBond.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/transact.js",
    "file/packages/oo7-substrate/src/transact.js.html",
    "packages/oo7-substrate/src/transact.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/types.js",
    "file/packages/oo7-substrate/src/types.js.html",
    "packages/oo7-substrate/src/types.js",
    "file"
  ],
  [
    "packages/oo7-substrate/src/utils.js",
    "file/packages/oo7-substrate/src/utils.js.html",
    "packages/oo7-substrate/src/utils.js",
    "file"
  ],
  [
    "packages/oo7/index.js",
    "file/packages/oo7/index.js.html",
    "packages/oo7/index.js",
    "file"
  ],
  [
    "packages/oo7/src/bond.js",
    "file/packages/oo7/src/bond.js.html",
    "packages/oo7/src/bond.js",
    "file"
  ],
  [
    "packages/oo7/src/bond.js~bond#_defaultto",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_defaultTo",
    "packages/oo7/src/bond.js~Bond#_defaultTo",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_maybenull",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_mayBeNull",
    "packages/oo7/src/bond.js~Bond#_mayBeNull",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_notreadybond",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_notReadyBond",
    "packages/oo7/src/bond.js~Bond#_notReadyBond",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_notifies",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_notifies",
    "packages/oo7/src/bond.js~Bond#_notifies",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_parse",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_parse",
    "packages/oo7/src/bond.js~Bond#_parse",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_ready",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_ready",
    "packages/oo7/src/bond.js~Bond#_ready",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_readybond",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_readyBond",
    "packages/oo7/src/bond.js~Bond#_readyBond",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_stringify",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_stringify",
    "packages/oo7/src/bond.js~Bond#_stringify",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_subscribers",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_subscribers",
    "packages/oo7/src/bond.js~Bond#_subscribers",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_thens",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_thens",
    "packages/oo7/src/bond.js~Bond#_thens",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_triggering",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_triggering",
    "packages/oo7/src/bond.js~Bond#_triggering",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_users",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_users",
    "packages/oo7/src/bond.js~Bond#_users",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_uuid",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_uuid",
    "packages/oo7/src/bond.js~Bond#_uuid",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#_value",
    "class/packages/oo7/src/bond.js~Bond.html#instance-member-_value",
    "packages/oo7/src/bond.js~Bond#_value",
    "member"
  ],
  [
    "packages/oo7/src/bond.js~bond#changed",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-changed",
    "packages/oo7/src/bond.js~Bond#changed",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#constructor",
    "class/packages/oo7/src/bond.js~Bond.html#instance-constructor-constructor",
    "packages/oo7/src/bond.js~Bond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#default",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-default",
    "packages/oo7/src/bond.js~Bond#default",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#defaultto",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-defaultTo",
    "packages/oo7/src/bond.js~Bond#defaultTo",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#done",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-done",
    "packages/oo7/src/bond.js~Bond#done",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#drop",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-drop",
    "packages/oo7/src/bond.js~Bond#drop",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#finalise",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-finalise",
    "packages/oo7/src/bond.js~Bond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#initialise",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-initialise",
    "packages/oo7/src/bond.js~Bond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#isdone",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-isDone",
    "packages/oo7/src/bond.js~Bond#isDone",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#isready",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-isReady",
    "packages/oo7/src/bond.js~Bond#isReady",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#latched",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-latched",
    "packages/oo7/src/bond.js~Bond#latched",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#log",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-log",
    "packages/oo7/src/bond.js~Bond#log",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#map",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-map",
    "packages/oo7/src/bond.js~Bond#map",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#mapeach",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-mapEach",
    "packages/oo7/src/bond.js~Bond#mapEach",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#maptostring",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-mapToString",
    "packages/oo7/src/bond.js~Bond#mapToString",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#notready",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-notReady",
    "packages/oo7/src/bond.js~Bond#notReady",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#notify",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-notify",
    "packages/oo7/src/bond.js~Bond#notify",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#ready",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-ready",
    "packages/oo7/src/bond.js~Bond#ready",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#reduce",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-reduce",
    "packages/oo7/src/bond.js~Bond#reduce",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#reset",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-reset",
    "packages/oo7/src/bond.js~Bond#reset",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#sub",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-sub",
    "packages/oo7/src/bond.js~Bond#sub",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#subscriptable",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-subscriptable",
    "packages/oo7/src/bond.js~Bond#subscriptable",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#then",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-then",
    "packages/oo7/src/bond.js~Bond#then",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#tie",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-tie",
    "packages/oo7/src/bond.js~Bond#tie",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#tostring",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-toString",
    "packages/oo7/src/bond.js~Bond#toString",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#trigger",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-trigger",
    "packages/oo7/src/bond.js~Bond#trigger",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#unnotify",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-unnotify",
    "packages/oo7/src/bond.js~Bond#unnotify",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#untie",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-untie",
    "packages/oo7/src/bond.js~Bond#untie",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#use",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-use",
    "packages/oo7/src/bond.js~Bond#use",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond#xform",
    "class/packages/oo7/src/bond.js~Bond.html#instance-method-xform",
    "packages/oo7/src/bond.js~Bond#xform",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond._fromsymbol",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-_fromSymbol",
    "packages/oo7/src/bond.js~Bond._fromSymbol",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond._knowsymbol",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-_knowSymbol",
    "packages/oo7/src/bond.js~Bond._knowSymbol",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond.all",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-all",
    "packages/oo7/src/bond.js~Bond.all",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond.instanceof",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-instanceOf",
    "packages/oo7/src/bond.js~Bond.instanceOf",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond.mapall",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-mapAll",
    "packages/oo7/src/bond.js~Bond.mapAll",
    "method"
  ],
  [
    "packages/oo7/src/bond.js~bond.promise",
    "class/packages/oo7/src/bond.js~Bond.html#static-method-promise",
    "packages/oo7/src/bond.js~Bond.promise",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js",
    "file/packages/oo7/src/bondCache.js.html",
    "packages/oo7/src/bondCache.js",
    "file"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#changed",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-changed",
    "packages/oo7/src/bondCache.js~BondCache#changed",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#checkconsistency",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-checkConsistency",
    "packages/oo7/src/bondCache.js~BondCache#checkConsistency",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#constructor",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-constructor-constructor",
    "packages/oo7/src/bondCache.js~BondCache#constructor",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#deferparentprefix",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-member-deferParentPrefix",
    "packages/oo7/src/bondCache.js~BondCache#deferParentPrefix",
    "member"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#ensureactive",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-ensureActive",
    "packages/oo7/src/bondCache.js~BondCache#ensureActive",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#finalise",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-finalise",
    "packages/oo7/src/bondCache.js~BondCache#finalise",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#initialise",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-initialise",
    "packages/oo7/src/bondCache.js~BondCache#initialise",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#onmessage",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-onMessage",
    "packages/oo7/src/bondCache.js~BondCache#onMessage",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#onstoragechanged",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-onStorageChanged",
    "packages/oo7/src/bondCache.js~BondCache#onStorageChanged",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#onunload",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-onUnload",
    "packages/oo7/src/bondCache.js~BondCache#onUnload",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#reconstruct",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-method-reconstruct",
    "packages/oo7/src/bondCache.js~BondCache#reconstruct",
    "method"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#regs",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-member-regs",
    "packages/oo7/src/bondCache.js~BondCache#regs",
    "member"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#sessionid",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-member-sessionId",
    "packages/oo7/src/bondCache.js~BondCache#sessionId",
    "member"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#storage",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-member-storage",
    "packages/oo7/src/bondCache.js~BondCache#storage",
    "member"
  ],
  [
    "packages/oo7/src/bondcache.js~bondcache#window",
    "class/packages/oo7/src/bondCache.js~BondCache.html#instance-member-window",
    "packages/oo7/src/bondCache.js~BondCache#window",
    "member"
  ],
  [
    "packages/oo7/src/bondproxy.js",
    "file/packages/oo7/src/bondProxy.js.html",
    "packages/oo7/src/bondProxy.js",
    "file"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#bonds",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-member-bonds",
    "packages/oo7/src/bondProxy.js~BondProxy#bonds",
    "member"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#constructor",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-constructor-constructor",
    "packages/oo7/src/bondProxy.js~BondProxy#constructor",
    "method"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#deferparentprefix",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-member-deferParentPrefix",
    "packages/oo7/src/bondProxy.js~BondProxy#deferParentPrefix",
    "member"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#fromuuid",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-member-fromUuid",
    "packages/oo7/src/bondProxy.js~BondProxy#fromUuid",
    "member"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#onmessage",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-method-onMessage",
    "packages/oo7/src/bondProxy.js~BondProxy#onMessage",
    "method"
  ],
  [
    "packages/oo7/src/bondproxy.js~bondproxy#window",
    "class/packages/oo7/src/bondProxy.js~BondProxy.html#instance-member-window",
    "packages/oo7/src/bondProxy.js~BondProxy#window",
    "member"
  ],
  [
    "packages/oo7/src/defaultbond.js",
    "file/packages/oo7/src/defaultBond.js.html",
    "packages/oo7/src/defaultBond.js",
    "file"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#_notifyid",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-member-_notifyId",
    "packages/oo7/src/defaultBond.js~DefaultBond#_notifyId",
    "member"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#_poll",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-member-_poll",
    "packages/oo7/src/defaultBond.js~DefaultBond#_poll",
    "member"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#_targetbond",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-member-_targetBond",
    "packages/oo7/src/defaultBond.js~DefaultBond#_targetBond",
    "member"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#constructor",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-constructor-constructor",
    "packages/oo7/src/defaultBond.js~DefaultBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#finalise",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-method-finalise",
    "packages/oo7/src/defaultBond.js~DefaultBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/defaultbond.js~defaultbond#initialise",
    "class/packages/oo7/src/defaultBond.js~DefaultBond.html#instance-method-initialise",
    "packages/oo7/src/defaultBond.js~DefaultBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/index.js",
    "file/packages/oo7/src/index.js.html",
    "packages/oo7/src/index.js",
    "file"
  ],
  [
    "packages/oo7/src/latchbond.js",
    "file/packages/oo7/src/latchBond.js.html",
    "packages/oo7/src/latchBond.js",
    "file"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#_notifyid",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-member-_notifyId",
    "packages/oo7/src/latchBond.js~LatchBond#_notifyId",
    "member"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#_poll",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-member-_poll",
    "packages/oo7/src/latchBond.js~LatchBond#_poll",
    "member"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#_ready",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-member-_ready",
    "packages/oo7/src/latchBond.js~LatchBond#_ready",
    "member"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#_targetbond",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-member-_targetBond",
    "packages/oo7/src/latchBond.js~LatchBond#_targetBond",
    "member"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#_value",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-member-_value",
    "packages/oo7/src/latchBond.js~LatchBond#_value",
    "member"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#constructor",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-constructor-constructor",
    "packages/oo7/src/latchBond.js~LatchBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#finalise",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-method-finalise",
    "packages/oo7/src/latchBond.js~LatchBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/latchbond.js~latchbond#initialise",
    "class/packages/oo7/src/latchBond.js~LatchBond.html#instance-method-initialise",
    "packages/oo7/src/latchBond.js~LatchBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/notreadybond.js",
    "file/packages/oo7/src/notReadyBond.js.html",
    "packages/oo7/src/notReadyBond.js",
    "file"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#_notifyid",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-member-_notifyId",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#_notifyId",
    "member"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#_poll",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-member-_poll",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#_poll",
    "member"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#_targetbond",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-member-_targetBond",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#_targetBond",
    "member"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#constructor",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-constructor-constructor",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#finalise",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-method-finalise",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/notreadybond.js~notreadybond#initialise",
    "class/packages/oo7/src/notReadyBond.js~NotReadyBond.html#instance-method-initialise",
    "packages/oo7/src/notReadyBond.js~NotReadyBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/reactivebond.js",
    "file/packages/oo7/src/reactiveBond.js.html",
    "packages/oo7/src/reactiveBond.js",
    "file"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_active",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_active",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_active",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_args",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_args",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_args",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_dependencies",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_dependencies",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_dependencies",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_execute",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_execute",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_execute",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_executereset",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_executeReset",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_executeReset",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_notified",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-method-_notified",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_notified",
    "method"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_notifykeys",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_notifyKeys",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_notifyKeys",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#_resolvedepth",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-member-_resolveDepth",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#_resolveDepth",
    "member"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#constructor",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-constructor-constructor",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#finalise",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-method-finalise",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/reactivebond.js~reactivebond#initialise",
    "class/packages/oo7/src/reactiveBond.js~ReactiveBond.html#instance-method-initialise",
    "packages/oo7/src/reactiveBond.js~ReactiveBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/reactivepromise.js",
    "file/packages/oo7/src/reactivePromise.js.html",
    "packages/oo7/src/reactivePromise.js",
    "file"
  ],
  [
    "packages/oo7/src/reactivepromise.js~reactivepromise#constructor",
    "class/packages/oo7/src/reactivePromise.js~ReactivePromise.html#instance-constructor-constructor",
    "packages/oo7/src/reactivePromise.js~ReactivePromise#constructor",
    "method"
  ],
  [
    "packages/oo7/src/readybond.js",
    "file/packages/oo7/src/readyBond.js.html",
    "packages/oo7/src/readyBond.js",
    "file"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#_notifyid",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-member-_notifyId",
    "packages/oo7/src/readyBond.js~ReadyBond#_notifyId",
    "member"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#_poll",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-member-_poll",
    "packages/oo7/src/readyBond.js~ReadyBond#_poll",
    "member"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#_targetbond",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-member-_targetBond",
    "packages/oo7/src/readyBond.js~ReadyBond#_targetBond",
    "member"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#constructor",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-constructor-constructor",
    "packages/oo7/src/readyBond.js~ReadyBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#finalise",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-method-finalise",
    "packages/oo7/src/readyBond.js~ReadyBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/readybond.js~readybond#initialise",
    "class/packages/oo7/src/readyBond.js~ReadyBond.html#instance-method-initialise",
    "packages/oo7/src/readyBond.js~ReadyBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/timebond.js",
    "file/packages/oo7/src/timeBond.js.html",
    "packages/oo7/src/timeBond.js",
    "file"
  ],
  [
    "packages/oo7/src/timebond.js~timebond#constructor",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#instance-constructor-constructor",
    "packages/oo7/src/timeBond.js~TimeBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/timebond.js~timebond#finalise",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#instance-method-finalise",
    "packages/oo7/src/timeBond.js~TimeBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/timebond.js~timebond#initialise",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#instance-method-initialise",
    "packages/oo7/src/timeBond.js~TimeBond#initialise",
    "method"
  ],
  [
    "packages/oo7/src/timebond.js~timebond#interval",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#instance-member-interval",
    "packages/oo7/src/timeBond.js~TimeBond#interval",
    "member"
  ],
  [
    "packages/oo7/src/timebond.js~timebond#poll",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#instance-method-poll",
    "packages/oo7/src/timeBond.js~TimeBond#poll",
    "method"
  ],
  [
    "packages/oo7/src/timebond.js~timebond.testintervals",
    "class/packages/oo7/src/timeBond.js~TimeBond.html#static-method-testIntervals",
    "packages/oo7/src/timeBond.js~TimeBond.testIntervals",
    "method"
  ],
  [
    "packages/oo7/src/transformbond.js",
    "file/packages/oo7/src/transformBond.js.html",
    "packages/oo7/src/transformBond.js",
    "file"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond#_outbond",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#instance-member-_outBond",
    "packages/oo7/src/transformBond.js~TransformBond#_outBond",
    "member"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond#constructor",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#instance-constructor-constructor",
    "packages/oo7/src/transformBond.js~TransformBond#constructor",
    "method"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond#dropout",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#instance-method-dropOut",
    "packages/oo7/src/transformBond.js~TransformBond#dropOut",
    "method"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond#finalise",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#instance-method-finalise",
    "packages/oo7/src/transformBond.js~TransformBond#finalise",
    "method"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond#useout",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#instance-method-useOut",
    "packages/oo7/src/transformBond.js~TransformBond#useOut",
    "method"
  ],
  [
    "packages/oo7/src/transformbond.js~transformbond.setdefaultcontext",
    "class/packages/oo7/src/transformBond.js~TransformBond.html#static-method-setDefaultContext",
    "packages/oo7/src/transformBond.js~TransformBond.setDefaultContext",
    "method"
  ],
  [
    "packages/polkadot-identicon/lib/index.js",
    "file/packages/polkadot-identicon/lib/index.js.html",
    "packages/polkadot-identicon/lib/index.js",
    "file"
  ],
  [
    "packages/polkadot-identicon/lib/index.js~identicon#constructor",
    "class/packages/polkadot-identicon/lib/index.js~Identicon.html#instance-constructor-constructor",
    "packages/polkadot-identicon/lib/index.js~Identicon#constructor",
    "method"
  ],
  [
    "packages/polkadot-identicon/lib/index.js~identicon#render",
    "class/packages/polkadot-identicon/lib/index.js~Identicon.html#instance-method-render",
    "packages/polkadot-identicon/lib/index.js~Identicon#render",
    "method"
  ]
]